id: I94BB7B4F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:06:52+00:00'
last_modified: '2022-06-07T17:49:33.344847+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD3927
  title: སངས་རྒྱས་ཀྱི་གཙུག་ཏོར་དཔའ་བར་འགྲོ་བ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D818:
      image_group_id: I4PD3929
      title: ''
      total_pages: 364
      order: 1
      base_file: D818.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
