id: P003134
initial_creation_type: ocr
source_metadata:
  id: bdr:W4PD3927
  title: སངས་རྒྱས་ཀྱི་གཙུག་ཏོར་དཔའ་བར་འགྲོ་བ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
  author: ''
  volumes:
    9ce08642feed465da7fb5b737e3e4081:
      image_group_id: I4PD3929
      title: ''
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
